[package]
name = "fuzion-std"
version = "0.8.0"
edition = "2021"
authors = ["Fuzion Works"]
description = "Standard Library and Utilities for Smart Contracts on Fuzion"
license = "Apache-2.0"
repository = "https://github.com/FuzionWorks/fuzion-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
hex = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
cw20 = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
